sudo: required

language: ruby

env:
  - DB=postgresql

services:
  - docker

before_install:
  - docker build -t chrisgeek/hospital-sys .

before_script:
  - cp config/database.travis.yml config/database.yml

script:
  - docker run chrisgeek/hospital-sys rspec spec 
