sudo: required

language: ruby

services:
  - docker
  - postgresql
language: ruby

before_install:
  - docker-compose build
  - docker-compose up -d && docker ps
env:
  - RAILS_ENV=test

script:
  - docker-compose run web bin/rake db:create db:migrate
  - docker-compose run web bin/bundle exec rspec
